os:
  - linux
  - osx
env:
  - EMACS=emacs-snapshot
before_install: |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update
    brew install emacs
    brew install ispell --with-lang-en
  fi
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sudo add-apt-repository -y ppa:cassou/emacs
    sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
    sudo apt-get update -qq
    sudo apt-get install -qq -yy ${EMACS}-nox ${EMACS}-el
  fi
script: |
  ./setup.sh
notifications:
  email: false
